### ISSUE TITLE
运行 ping.py时报错

### ISSUE THREAD

**Issue by crazy-zhangcong** [chuanwu/WechatBot#28]
[root@crazy-acong wechatbot]# python ping.py
Traceback (most recent call last):
  File "ping.py", line 2, in <module>
    from wechatbot import WechatBot
  File "/usr/local/lib/python2.7/site-packages/wechatbot/__init__.py", line 2, in <module>
    from wechatbot.bot import WechatBot
  File "/usr/local/lib/python2.7/site-packages/wechatbot/bot.py", line 13, in <module>
    import qrcode
  File "/usr/local/lib/python2.7/site-packages/qrcode/__init__.py", line 1, in <module>
    from qrcode.main import QRCode
  File "/usr/local/lib/python2.7/site-packages/qrcode/main.py", line 1, in <module>
    from qrcode import constants, exceptions, util
  File "/usr/local/lib/python2.7/site-packages/qrcode/util.py", line 4, in <module>
    import six
ImportError: No module named six

**Comment by crazy-zhangcong** [comment]
解决方法：[root@crazy-acong wechatbot]# pip2.7 install six

**Comment by chuanwu** [comment]
你安装的six版本是？

**Comment by crazy-zhangcong** [comment]
six (1.10.0)
